export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export const SHOW_GLOBAL_NOTIFICATION = 'SHOW_GLOBAL_NOTIFICATION';
export const REMOVE_GLOBAL_NOTIFICATION = 'REMOVE_GLOBAL_NOTIFICATION';

export const SHOW_ALERT = 'SHOW_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SET_LOGIN_TOKEN = 'SET_LOGIN_TOKEN';
export const REMOVE_LOGIN_TOKEN = 'REMOVE_LOGIN_TOKEN';
export const RECEIVE_LOGIN_TOKEN = 'RECEIVE_LOGIN_TOKEN';
export const RESET_STORE = 'RESET_STORE';

export const RECEIVE_REGISTER = 'RECEIVE_REGISTER';
export const CONFIRM_EMAIL = 'CONFIRM_MAIL';

export const PROFILE_LOADED = 'PROFILE_LOADED';
export const SET_PROFILE = 'SET_PROFILE';

export const RECEIVE_WALLET = 'RECEIVE_WALLET';
export const SET_WALLET = 'SET_WALLET';
export const UNSET_WALLET = 'UNSET_WALLET';
export const UPDATE_WALLET = 'UPDATE_WALLET';

export const RECEIVE_STRATEGY = 'RECEIVE_STRATEGY';
export const SET_STRATEGY = 'SET_STRATEGY';
export const UNSET_STRATEGY = 'UNSET_STRATEGY';
export const RESET_STRATEGY = 'RESET_STRATEGY';
export const FOLLOW_STRATEGY = 'FOLLOW_STRATEGY';
export const RESET_FOLLOWING_STRATEGIES = 'RESET_FOLLOWING_STRATEGIES';
export const SUBSCRIBE_STRATEGY = 'SUBSCRIBE_STRATEGY';

export const RECEIVE_STRATEGIES = 'RECEIVE_STRATEGIES';
export const SET_STRATEGIES = 'SET_STRATEGIES';
export const RESET_STRATEGIES = 'RESET_STRATEGIES';

export const RECEIVE_FOLLOWING_STRATEGIES = 'RECEIVE_FOLLOWING_STRATEGIES';
export const SET_FOLLOWING_STRATEGIES = 'SET_FOLLOWING_STRATEGIES';
export const UPDATE_FOLLOWING_STRATEGIES = 'UPDATE_FOLLOWING_STRATEGIES';

export const RECEIVE_STRATEGY_SIGNALS = 'RECEIVE_STRATEGY_SIGNALS';
export const SET_STRATEGY_SIGNALS = 'SET_STRATEGY_SIGNALS';

export const RECEIVE_CANDLES = 'RECEIVE_CANDLES';
export const SET_CANDLES = 'SET_CANDLES';
export const RESET_CANDLES = 'RESET_CANDLES';

export const SET_EDITED_STRATEGY = 'SET_EDITED_STRATEGY';
export const EDITED_STRATEGY_LOADED = 'EDITED_STRATEGY_LOADED';
export const SET_MARKETS = 'SET_MARKETS';
export const SET_INDICATORS = 'SET_INDICATORS';
export const UNSET_EDITED_STRATEGY = 'UNSET_EDITED_STRATEGY';
export const MARKETS_LOADED = 'MARKETS_LOADED';
export const INDICATORS_LOADED = 'INDICATORS_LOADED';

export const RECEIVE_USER_STRATEGIES = 'RECEIVE_USER_STRATEGIES';
export const SET_USER_STRATEGIES = 'SET_USER_STRATEGIES';
export const RESET_USER_STRATEGIES = 'RESET_USER_STRATEGIES';

export const WEBSOCKET_DISCONNECT = 'WEBSOCKET_DISCONNECT';
export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
export const WEBSOCKET_RECONNECT = 'WEBSOCKET_RECONNECT';

export const RECEIVE_SIGNALS = 'RECEIVE_SIGNALS';
export const SET_SIGNAL = 'SET_SIGNAL';
export const RECEIVE_SIGNAL = 'RECEIVE_SIGNAL';

export const SET_SIGNALS = 'SET_SIGNALS';
export const RESET_SIGNALS = 'RESET_SIGNALS';
