#!/bin/bash
php ../bin/console doctrine:fixtures:load --append
echo "___________________________________________________________"
echo "* Spawned new users with related login data:"
echo -e " 1)   [email ] : root@root.com" 
echo -e "      [passwd] : root"
echo "-----------------------------------------------------------"
echo -e " 2)   [email ] : andrew@rgmail.com" 
echo -e "      [passwd] : andrew"
echo -e " 	    - Strategy :" 
echo -e "      		[name   ] : "Andrew Prediction""
echo -e "      		[api_key] : babushkinandrewbabushkinandrew01"
echo "-----------------------------------------------------------"
echo -e " 3)   [email ] : niki@gmail.com" 
echo -e "      [passwd] : niki"
echo -e " 	    - Wallet :" 
echo -e "      		[balance] : 400000.5"
echo -e "      	  (Subscribed to "Andrew Prediction" strategy)"
echo "-----------------------------------------------------------"
echo -e "     Your Clearing Center team.."